import Head from "next/head";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";
import btnStyles from "@/styles/Button.module.css";
import { Box, Container, Paper, Select, TextField } from "@mui/material";
import CustomButton from "@/components/CustomButton";
import AddIcon from "@mui/icons-material/Add";
import DataTable from "@/components/DataTable";
import { data } from "@/utils/data.js";
import { userColumns } from "@/utils/column.js";
import Search from "@/components/Search";
import {  use, useEffect, useState } from "react";
import AddEditModal from "@/components/modal/AddEditModal";
import { getUserDataFromStorage, setUserDataToStorage } from "@/utils/localStorageData";
import DeleteModal from "@/components/modal/DeleteModal";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  
  
  const[addOpen, setAddOpen] = useState(false);
  const [userData, setUserData] = useState(data); 
  useEffect(() => {
    const stored = getUserDataFromStorage();    
    if (stored.length === 0) {
      setUserData(data);
      setUserDataToStorage(data);
    } else {
      setUserData(stored);
    }
  }, []);
  
  return (
    <>
      <Head>
        <title>Data Table Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box className={`${geistSans.variable} ${geistMono.variable}`}>
        <main className={styles.main}>
          <Container maxWidth="xl" className={styles.container}>
            <Paper elevation={3} className={styles.paper}>
              <h1 className={styles.title}>Welcome to the Data Table App</h1>
              <Box className={btnStyles.buttonContainer}>
                <CustomButton
                  variant="outlined"
                  label="Add User"
                  startIcon={<AddIcon />}
                  onClick={() => setAddOpen(true)}
                />
              </Box>
              <Box className={styles.searchContainer}>
                <Search type={"text"} />
              </Box>
              <DataTable userData={userData} columns={userColumns} />
            </Paper>
          </Container>
        </main>
      </Box>
      {/* This modal for add user */}
      <AddEditModal open={addOpen} userData={userData} setUserData={setUserData} onClose={() => {setAddOpen(false)}}  title={"Add User Details"} />
      <DeleteModal/>
    </>
  );
}
